# Generated by Django 5.0.2 on 2024-03-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="gender",
            field=models.CharField(
                choices=[("M", "Men"), ("W", "Women"), ("K", "Kids")], max_length=1
            ),
        ),
    ]
