# Generated by Django 5.0.2 on 2024-03-28 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_product_size_alter_category_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
    ]
