# Generated by Django 5.0.2 on 2024-04-05 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommended",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=False,
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Product name can only contain letters, numbers, spaces, '?','&', '!', '^','-','_','.', hyphens, and apostrophe characters.",
                                regex="^[A-Za-z0-9?!,.\\'\\s-]+$",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField()),
                ("image_1", models.ImageField(default="", upload_to="Recommended")),
                ("image_2", models.ImageField(default="", upload_to="Recommended")),
                ("image_3", models.ImageField(default="", upload_to="Recommended")),
                ("image_4", models.ImageField(default="", upload_to="Recommended")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Men"), ("W", "Women"), ("K", "Kids")],
                        max_length=1,
                    ),
                ),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
